CREATE TABLE IF NOT EXISTS USERS (
    USER_ID BINARY(16) NOT NULL,
    USERNAME VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    ROLE VARCHAR(50) NOT NULL,
    CREATED_AT DATETIME(6) NOT NULL,
    UPDATED_AT DATETIME(6) NOT NULL,
    PRIMARY KEY (USER_ID),
    INDEX IDX_USER_USERNAME (USERNAME),
    INDEX IDX_USER_CREATED_AT (CREATED_AT)
);

CREATE TABLE IF NOT EXISTS PROFILES (
    PROFILE_ID BINARY(16) NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    CONTENT TEXT NOT NULL,
    IS_DELETED BOOLEAN NOT NULL,
    VIEW_COUNT BIGINT NOT NULL,
    USER_ID BINARY(16) NOT NULL UNIQUE,
    USERNAME VARCHAR(255) NOT NULL UNIQUE,
    CREATED_AT DATETIME(6) NOT NULL,
    UPDATED_AT DATETIME(6) NOT NULL,
    PRIMARY KEY (PROFILE_ID),
    INDEX IDX_PROFILE_USERID (USER_ID),
    INDEX IDX_PROFILE_USERNAME (USERNAME),
    INDEX IDX_PROFILE_TITLE (TITLE),
    INDEX IDX_PROFILE_CREATED_AT (CREATED_AT)
);

CREATE TABLE IF NOT EXISTS PROFILES_VIEWS (
    PROFILE_VIEW_ID BIGINT NOT NULL AUTO_INCREMENT,
    PROFILE_ID BINARY(16) NOT NULL,
    VIEWED_AT DATETIME(6) NOT NULL,
    PRIMARY KEY (PROFILE_VIEW_ID),
    FOREIGN KEY (PROFILE_ID) REFERENCES PROFILES(PROFILE_ID) ON DELETE CASCADE,
    INDEX IDX_PROFILE_VIEWED_PROFILE_ID (PROFILE_ID)
);
